sonar.projectKey=cost-tracker-app
sonar.projectName=cost-tracker-app
sonar.projectVersion=1.0.0

sonar.sources=src,db
sonar.exclusions=**/node_modules/**,**/dist/**,**/routeTree.gen.ts

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
